[PROTOCOL-267] Limit Escrow interaction with unsecured loans.
teller-protocol/teller-protocol-v1 pull request #179
Opened 2020-09-16 00:03 UTC by passabilities

It:
* Restricts interactions for Escrows that are for an unsecured loan to Dapps that are marked as `unsecured`

2020-09-17 15:55 UTC, salazarguille requested changes

2020-09-17 15:55 UTC, salazarguille commented on contracts/base/LoansBase.sol
> +    function isLoanSecured(uint256 loanID) external view returns (bool) {
Please, add docs.

2020-09-18 18:11 UTC, salazarguille approved these changes
LGTM

2020-09-18 18:53 UTC, sypeer approved these changes

2020-09-19 16:26 UTC, merged