[PROTOCOL-419] [L08] Naming hinders code understanding and readability
teller-protocol/teller-protocol-v1 pull request #245
Opened 2020-12-27 02:38 UTC by sypeer

It is:
- Renamed names of the functions and contracts for better readability

2020-12-30 16:57 UTC, passabilities requested changes
* Keep the naming of `supplyToDebt` and inverse the ratio for the calculation.
* Rename all interfaces to be prefixed with **I** (ex: `IBaseProxy.sol`) instead of the postfix **Interface** (ex: `BaseProxyInterface.sol`)

2021-01-01 22:38 UTC, sypeer commented
> * Keep the naming of `supplyToDebt` and inverse the ratio for the calculation.
> * Rename all interfaces to be prefixed with **I** (ex: `IBaseProxy.sol`) instead of the postfix **Interface** (ex: `BaseProxyInterface.sol`)

Done dawg

2021-01-06 03:06 UTC, salazarguille requested changes
Great Job Syed, I know it was a heavy change.

Please, verify the CI, and check if the integration tests are  passing.

2021-01-06 13:11 UTC, hensha256 reviewed
Well done @sypeer

2021-01-06 13:11 UTC, hensha256 commented on test/base/MarketsStateGetDebtRatioForTest.js
> +contract('MarketsStateGetDebtToSupplyForTest', function (accounts) {
Most of this PR has the new wording has 'Debt Ratio' not 'DebtToSupply'?

2021-01-06 13:11 UTC, hensha256 commented on test/base/MarketsStateGetSupplyToDebtTest.js
> +contract('MarketsStateGetDebtToSupplyTest', function (accounts) {
Same here

2021-03-13 01:20 UTC, closed without merging