[PROTOCOL-409] [C01]: Interest outcome can be manipulated
teller-protocol/teller-protocol-v1 pull request #264
Opened 2021-01-08 13:36 UTC by tpscrpt

Fix adds a modifier to the Consensus contract requiring that the number of responses in the call is greater than or equal to number of singers - 1. Number of signers tracked when _addSigner and _removeSigner is called on OwnerSignersRole.

2021-01-08 17:25 UTC, passabilities commented on contracts/base/InterestConsensus.sol
> -                    _getSettings().consts().REQUIRED_SUBMISSIONS_SETTING()
Why are we not using the platform setting value anymore?

2021-01-10 00:31 UTC, tpscrpt commented
@passabilities Ready for review

2021-01-10 23:20 UTC, passabilities requested changes

2021-01-10 23:20 UTC, passabilities commented on contracts/base/Consensus.sol
> +        );
I don't think this is correct:
```
signers = 6
percentRequired = 8000

signers * percentRequired + 9999 / 10000 = 48000.9999
```

We could use `NumbersLib.ratioOf()` to get the ratio of signers from the `responseCount` and then compare it to the platform setting. That way we don't have to worry about the rounding issue of getting 80% of 6 which would chop off the decimals.

Heres what I'm thinking:
```
uint256 signersRatio = responseCount.ratioOf(_signersCount);
// signersRatio = 6 * 10000 / 8 = 7500
require(signersRatio >= percentageRequired);
```

2021-01-11 00:27 UTC, passabilities approved these changes

2021-01-11 01:43 UTC, merged