[PROTOCOL-350] and [348]. Moving accrued interest on-chain
teller-protocol/teller-protocol-v1 pull request #267
Opened 2021-01-10 12:05 UTC by hensha256

2021-01-10 19:58 UTC, passabilities requested changes
Looks good and definitely cleans up the code base as well! 

NOTE: Please rebase this or merge in the branch `feature/merge-LP-MS` as I get rid of the `MarkesState` contract and merge the functionality directly into the `LendingPool`

2021-01-10 19:58 UTC, passabilities commented on contracts/base/LendingPool.sol
> +        );
why are we multiplying by 18? did you mean `10**18`?

2021-01-10 19:58 UTC, passabilities commented on contracts/base/LendingPool.sol
> +        );
whats this?

2021-01-10 19:58 UTC, passabilities commented on contracts/base/LendingPool.sol
> +        exchangeRate = totalLendingToken.mul(EXCHANGE_RATE_DECIMALS).div(totalTToken);
again here

2021-01-10 19:58 UTC, passabilities commented on contracts/interfaces/TTokenInterface.sol
> +
could just make this extend the new `IERC20Detailed` Interface instead

2021-01-10 19:58 UTC, passabilities commented on test/utils/logicNames.js
>      TokenCollateralLoans: 'TokenCollateralLoans',
above this line we can also remove the `Lenders`

2021-01-12 03:36 UTC, tpscrpt approved these changes

2021-01-13 03:33 UTC, salazarguille requested changes
Great job! @hensha256 
Just some comments/questions
- 2 tests are failing.
- are the integration tests passing?

2021-01-15 03:45 UTC, passabilities submitted a review, later dismissed

2021-01-15 17:48 UTC, passabilities approved these changes

2021-01-15 17:50 UTC, merged