Fix/protocol 520
teller-protocol/teller-protocol-v1 pull request #360
Opened 2021-05-18 21:30 UTC by dumebi

- test using existing or not

2021-05-20 23:06 UTC, passabilities requested changes

2021-05-20 23:06 UTC, passabilities commented on package.json
> +    "coverage": "yarn hh coverage --solcoverjs ./solcover.js",
can leave for coverage PR as well

2021-05-20 23:06 UTC, passabilities commented on package.json
> +    "solidity-coverage": "^0.7.16",
can leave for coverage PR as well

2021-05-20 23:06 UTC, passabilities commented on scripts/hh.sh
> +  run test localhost ${opts[*]}
can revert changes

2021-05-20 23:06 UTC, passabilities commented on utils/hre-extensions.ts
> +    }
I believe we should be able to get rid of this change as well honestly with the update to the `hardhat.config.ts`

2021-05-21 17:14 UTC, dumebi commented on .env.template
> +DEPLOYER=0xAFe87013dc96edE1E116a288D80FcaA0eFFE5fe5
do you mean the template file? or deployer address

2021-05-21 18:48 UTC, closed without merging