Memo
teller-protocol/teller-protocol-v1 pull request #364
Opened 2021-05-25 21:58 UTC by mkhoury93

2021-05-25 23:00 UTC, mrbaguvix approved these changes

2021-05-26 00:07 UTC, passabilities approved these changes

2021-05-26 18:26 UTC, mrbaguvix submitted a review, later dismissed

2021-05-31 05:54 UTC, passabilities approved these changes

2021-05-31 05:54 UTC, passabilities commented on contracts/cc/creditcard/CreditCard_V1.sol
> +// SPDX-License-Identifier: MIT
should remove file from PR

2021-05-31 05:54 UTC, passabilities commented on contracts/escrow/escrow/ILoansEscrow.sol
> +     * @notice it allows user to claim their escrow tokens
should also mention that only the `ower` (`TellerDiamond`) can make this call on behalf of the users

2021-05-31 05:54 UTC, passabilities commented on contracts/escrow/escrow/LoansEscrow_V1.sol
> +     * @notice it allows user to claim their escrow tokens
same ^

2021-05-31 05:54 UTC, passabilities commented on contracts/lending/ttoken/strategies/compound/TTokenCompoundStrategy_1.sol
> +     */
change to 
> It creates a reference to the {TToken | Compound} storage // remove remaining of sentence

2021-05-31 05:54 UTC, passabilities commented on contracts/market/CreateLoanFacet.sol
> +     * @notice creates a new ID for the loan
change from `creates` to `increments`

2021-05-31 05:54 UTC, passabilities commented on contracts/market/CreateLoanFacet.sol
> +     * @notice it creates a new loan escrow for the respective loan to hold it's funds
> it creates a new loan escrow **contract**

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/CollateralEscrow_V1.sol
> +     * @notice it creates a escrow to store collateral tokens
> it **initializes an** escrow

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/CollateralEscrow_V1.sol
> +     * @notice it returns the total supply of our collateral token
> it returns the total supply of then collateral token held by the contract

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/ICollateralEscrow.sol
> +     * @notice it creates a escrow to store collateral tokens
same from above

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/ICollateralEscrow.sol
> +     * @notice it returns the total supply of our collateral token
same from above

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/CollateralEscrow_V1.sol
> +     * @notice it withdraws an amount of tokens in a respective loanID if the caller is the owner
actually only the `TellerDiamond` is able to call this on behalf of the borrower

2021-05-31 05:54 UTC, passabilities commented on contracts/market/collateral/ICollateralEscrow.sol
> +     * @notice it withdraws an amount of tokens in a respective loanID if the caller is the owner
same from above

2021-05-31 05:54 UTC, passabilities commented on contracts/market/libraries/LibConsensus.sol
> +            // check if the signature of
> check if the signature of hashed response data matches

2021-05-31 05:54 UTC, passabilities commented on contracts/market/libraries/LibLoans.sol
> +        //
can remove this but maybe add couple more comments for the functions above

2021-05-31 05:54 UTC, passabilities commented on contracts/nft/distributor/entry/initialize.sol
> + // SPDX-License-Identifier: MIT
can undo

2021-05-31 17:08 UTC, mrbaguvix approved these changes

2021-06-01 00:14 UTC, mkhoury93 commented
updated from your comments @passabilities !

2021-06-02 20:01 UTC, sypeer commented on contracts/nft/distributor/interfaces/ITellerNFTDistributor.sol
> +     * @notice
missing un?

2021-06-02 20:03 UTC, sypeer requested changes
Capin Memo's first strike! One small fix and looks good

2021-06-03 13:49 UTC, mkhoury93 commented
@sypeer play ball!

2021-06-03 15:25 UTC, sypeer approved these changes

2021-06-03 15:50 UTC, merged