Nftdictionary
teller-protocol/teller-protocol-v1 pull request #367
Opened 2021-05-29 04:33 UTC by admazzola

Adds the NFTDictionary contract to the project.  This serves as a data-store for metadata related to TellerNFTv1.  

Upon deployment, mass data is uploaded into the NFTDictionary contract.  When a new TellerNFT is claimed (minted) then its data is added to the NFTDictionary.

2021-05-31 05:23 UTC, passabilities requested changes

2021-05-31 05:23 UTC, passabilities commented on contracts/nft/TellerNFTDictionary.sol
> +    function setAllTokenTierMappings(uint256[] memory tiersMapping)
@admazzola please check the rest of the functions and add comments 🙏🏼

2021-05-31 05:23 UTC, passabilities commented on contracts/nft/TellerNFTDictionary.sol
> +    function tokenBaseLoanSize(uint256 tokenId)
Incorrect doc strings for this and functions below

2021-05-31 05:23 UTC, passabilities commented on contracts/nft/distributor/entry/claim.sol
> +            ///uint256[] preOwnedTokens = distributorStore().nft.getOwnedTokens(account);
can remove

2021-05-31 05:23 UTC, passabilities commented on contracts/nft/distributor/entry/claim.sol
> +            );
adding inline comments here would be super beneficial when we come back to this at a later point

2021-05-31 05:23 UTC, passabilities commented on tasks/fork.ts
> +  console.log('forking things', network)
can remove

2021-05-31 05:23 UTC, passabilities commented on test/integration/dictionary.test.ts
> +      }))*/
can remove

2021-05-31 05:23 UTC, passabilities commented on test/integration/dictionary.test.ts
> +          //await claimNFT({ account: borrower, merkleIndex:  merkleIndex+existingMerkles.length }, hre)
can remove

2021-05-31 05:23 UTC, passabilities commented on test/integration/dictionary.test.ts
> +          console.log(`merkleData.tierIndex was ${merkleData.tierIndex}`)
can remove

2021-05-31 05:23 UTC, passabilities commented on test/integration/dictionary.test.ts
> +          console.log(`merkle index ${merkleIndex + existingMerkles.length}`)
can remove

2021-05-31 05:23 UTC, passabilities commented on tasks/nft/add-nft-tiers.ts
> +  */
can remove

2021-05-31 05:23 UTC, passabilities commented on test/unit/nft-dictionary.test.ts
> +  });*/
needs to be implemented?

2021-05-31 05:23 UTC, passabilities commented on test/unit/nft-dictionary.test.ts
> +    console.log('tokenTiers length', tokenTiers.length)
can remove comments in file

2021-05-31 05:23 UTC, passabilities commented on utils/deploy-helpers.ts
> +      //args: args.args,
can remove

2021-06-02 00:15 UTC, closed without merging

2021-06-02 00:15 UTC, admazzola commented
Making a new pull request..