[PROTOCOL-634] [M01] Exchange rate rounding
teller-protocol/teller-protocol-v1 pull request #409
Opened 2021-06-28 22:02 UTC by dumebi

added a check to ensure the calculated amounts to mint, redeem and burn are non-zero

2021-06-29 14:26 UTC, mkhoury93 approved these changes

2021-06-29 14:52 UTC, sypeer submitted a review, later dismissed

2021-06-29 16:12 UTC, passabilities requested changes

2021-06-29 16:12 UTC, passabilities commented on contracts/lending/ttoken/TToken_V1.sol
>          uint256 tokenValue = _valueOfUnderlying(amount, rate);
In the interest of this comment

> Moreover, consider rounding up when calculating the [the number of tTokens to burn](https://github.com/teller-protocol/teller-protocol-v1/blob/cc80420ff73b0f7c466f6021ab57b2d71f96c3ba/contracts/lending/ttoken/TToken_V1.sol#L285).

lets append ` + 1`

2021-07-04 18:38 UTC, passabilities approved these changes

2021-07-04 18:38 UTC, merged