safecast the ratio to avoid future truncation of debt ratio
teller-protocol/teller-protocol-v1 pull request #420
Opened 2021-06-29 13:43 UTC by mkhoury93

2021-06-29 14:37 UTC, dumebi submitted a review, later dismissed

2021-06-29 16:25 UTC, passabilities requested changes

2021-06-29 16:25 UTC, passabilities commented on contracts/lending/ttoken/TToken_V1.sol
> +            );
I think given the comment from OZ, the `SafeCast.toUint16` should happen in the `NumbersLib.ratioOf` function. 

```solidity
        return num2 == 0 ? 0 : SafeCast.toUint16((num1 * ONE_HUNDRED_PERCENT) / num2);
```

2021-07-04 19:14 UTC, passabilities approved these changes

2021-07-04 19:26 UTC, merged