Update PriceAggregator logic
teller-protocol/teller-protocol-v1 pull request #436
Opened 2021-07-06 01:16 UTC by passabilities

* Uses ENS naming to look up `ChainlinkAggregator` addresses 
* Supports a modular pricing model where we can easily add pricing for single asset liquidity pool tokens that are not supported by Chainlink

2021-07-06 16:44 UTC, mkhoury93 requested changes

2021-07-06 16:44 UTC, mkhoury93 commented on contracts/shared/interfaces/ITellerDiamond.sol
> +import { SushiswapFacet } from "../../escrow/dapps/swappers/SushiswapFacet.sol";
we can remove these imports @passabilities

2021-07-07 02:51 UTC, admazzola approved these changes

2021-07-07 21:21 UTC, sypeer approved these changes

2021-07-07 21:27 UTC, merged