Feature/liquidate facet v2
teller-protocol/teller-protocol-v1 pull request #478
Opened 2021-08-17 20:58 UTC by admazzola

When a loan using an NFT is liquidated, the NFT is sent to a Gnosis Safe.  This only worked for NFTv1 so this PR also adds this functionality to NFTv2

2021-08-18 17:55 UTC, mkhoury93 requested changes

2021-08-18 17:55 UTC, mkhoury93 commented on contracts/market/RepayFacet.sol
> +import "hardhat/console.sol";
please remove this

2021-08-18 17:55 UTC, mkhoury93 commented on contracts/market/mainnet/MainnetRepayFacet.sol
> +        TELLER_NFT_V1 = TellerNFT(nftV1Address);
where are we using `TELLER_NFT_V1`

2021-08-19 18:12 UTC, admazzola commented on contracts/market/RepayFacet.sol
> +                "0x"
""

2021-08-19 18:16 UTC, admazzola commented on contracts/market/mainnet/MainnetRepayFacet.sol
> +       @notice On mainnet, we override the liquidateNFT method so that TellerNFTV1 is also transferred
asterisk

2021-08-19 18:18 UTC, admazzola commented on tasks/test.ts
> +  //  process.env.DISABLE_LOGS = 'true'
turn this back on

2021-08-19 18:20 UTC, admazzola commented on test/integration/liquidation.test.ts
> +              expect(loanData.status).to.equal(LoanStatus.Closed)
test liquidate in v1

2021-08-19 19:10 UTC, dwking2000 submitted a review, later dismissed
Looks good. Based on our walkthrough I have no comments.

2021-08-23 21:02 UTC, passabilities requested changes

2021-08-23 21:02 UTC, passabilities commented on contracts/market/RepayFacet.sol
> +
lets remove this

2021-08-23 21:02 UTC, passabilities commented on test/integration/loans.test.ts
> +
run `yarn format:write`

2021-08-23 21:56 UTC, passabilities approved these changes

2021-08-23 23:16 UTC, mkhoury93 approved these changes

2021-08-24 08:23 UTC, dumebi approved these changes

2021-08-24 14:36 UTC, merged