add V3
teller-protocol/teller-protocol-v1 pull request #480
Opened 2021-08-19 20:12 UTC by mkhoury93

Given that the user has a combination of V1 and V2 tokens, we need to combine both NFT ID types to take out a loan. It doesn't make sense for a user to discriminate between a V1 and a V2 token when they are just trying to take out a loan.

2021-08-20 14:02 UTC, dumebi requested changes

2021-08-20 14:02 UTC, dumebi commented on contracts/market/CreateLoanWithNFTFacet.sol
> +            uint256 loanSize1 = CreateLoanWithNFTFacet._takeOutLoanProcessNFTs(
if this is for allowed loan size, isn't it better to name them `allowedLoanSize1`, `allowedLoanSize2`?

2021-08-20 15:03 UTC, passabilities requested changes

2021-08-20 15:03 UTC, passabilities commented on contracts/market/CreateLoanWithNFTFacet.sol
> +        } else if (version == 3) {
lets leave this function to just have this (remove the `if` and `else`)
```solidity
            return _takeOutLoanProcessNFTs(loanID, version, tokenData_);
```

2021-08-20 15:03 UTC, passabilities commented on contracts/market/CreateLoanWithNFTFacet.sol
> +        } else if (version == 3) {
remove this `else if` from here. we will add the additional checks we need in the `MainnetCreateLoanWithNFTFacet`

2021-08-20 15:03 UTC, passabilities commented on contracts/market/mainnet/MainnetCreateLoanWithNFTFacet.sol
> +        } else if (version == 3) {
change this to the bitwise operations we went over, where the version is 3 we:

```solidity
uint256 v1Amount = ...;
uint256 v2Amount = super._takeOutLoanProcessNFTs(...);
allowedLoanSize_ = v1Amount + v2Amount;
```

2021-08-23 23:14 UTC, passabilities approved these changes

2021-08-24 08:24 UTC, dumebi approved these changes

2021-08-24 14:37 UTC, merged