[PROTOCOL-1267] Enabling eth deposits
teller-protocol/teller-protocol-v1 pull request #500
Opened 2021-10-27 19:38 UTC by sypeer

2021-10-27 19:42 UTC, passabilities requested changes
We'll also need to deposit into WETH as we are doing when depositing ETH as collateral in the `LibCollateral.deposit` function

2021-10-27 20:42 UTC, passabilities requested changes

2021-10-27 20:42 UTC, passabilities commented on contracts/lending/LendingFacet.sol
> +            ERC20WrapperUpgradeable(asset).depositFor(address(this), amount);
Lets create an `immutable` constant during facet deployment for the WETH address and `require(asset == WETH)` to ensure that we are correctly depositing ETH to the correct contract.

Also you need to modify this line to use [this interface](https://github.com/teller-protocol/teller-protocol-v1/blob/develop/contracts/shared/interfaces/IWETH.sol#L19):
```solidity
IWETH(asset).depositFor{ value: msg.value }();
```

2021-10-27 20:44 UTC, sypeer commented on contracts/lending/LendingFacet.sol
> +            ERC20WrapperUpgradeable(asset).depositFor(address(this), amount);
why not use the ERC20Wrapper interface?

2021-10-27 20:46 UTC, passabilities commented on contracts/lending/LendingFacet.sol
> +            ERC20WrapperUpgradeable(asset).depositFor(address(this), amount);
**ERC20WrapperUpgradeable**
![image](https://user-images.githubusercontent.com/6958300/139144398-525603b6-673e-4d81-b16b-4b3e31fdebc0.png)

**IWETH**
![image](https://user-images.githubusercontent.com/6958300/139144463-c51ac666-610b-4a89-85c7-46582e5c6559.png)

2021-10-27 22:06 UTC, sypeer commented on contracts/lending/LendingFacet.sol
> +            ERC20WrapperUpgradeable(asset).depositFor(address(this), amount);
using the `wrappedNativeToken` address from AppStorage instead of adding another immutable constant https://github.com/teller-protocol/teller-protocol-v1/blob/develop/contracts/storage/app.sol#L34

2021-10-27 22:19 UTC, passabilities requested changes

2021-10-27 22:19 UTC, passabilities commented on contracts/lending/LendingFacet.sol
> +            );
Lastly, since the end result of checking it there is a `msg.value` and depositing into WETH is that we for sure have an ERC20 token now to deal with, this block of code should be after the `if/else` and before the `safeTransfer` below as the `tToken.mint` function needs to pull in the tokens deposited

2021-11-03 16:35 UTC, passabilities approved these changes

2021-11-03 17:04 UTC, merged